version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: supplier_compliance_db
    environment:
      POSTGRES_DB: supplier_compliance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: supplier_compliance_api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/supplier_compliance_db
      GEMINI_API_KEY: AIzaSyD7Jy0XyzmmpmkSbR6IyUobyx4tXJ2cmF8
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    container_name: supplier_compliance_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
