"""add weather fields to compliance records

Revision ID: 002_add_weather_fields
Revises: 001_initial
Create Date: 2024-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_add_weather_fields'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_records', sa.Column('weather_data', sa.JSON(), nullable=True))
    op.add_column('compliance_records', sa.Column('weather_justification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_records', 'weather_justification')
    op.drop_column('compliance_records', 'weather_data')
    # ### end Alembic commands ###
